# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.15.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [54]:
tf.Session().run(hello)

b'Hello'

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [12]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [13]:
sess.close()

## Operations

In [14]:
const = tf.constant(10)
const

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [15]:
fill_mat = tf.fill((4,4),10)

In [16]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [17]:
myzeros = tf.zeros((4,4))
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [18]:
myones = tf.ones((4,4))
myones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [19]:
# myrandu = tf.random_normal_initializer((4,4))
# myrandu

In [21]:
# tf.random_uniform_initializer((4,4),minval=0, seed=123)

In [24]:
# this is not available in tensorflow 2.0
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
myrandn

<tf.Tensor 'random_normal_1:0' shape=(4, 4) dtype=float32>

In [43]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1,seed=123)

In [26]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [27]:
type(my_ops)

list

## Interactive Session

Useful for Notebook Sessions

In [41]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [47]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1,seed=123)
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.17018864  0.47338617 -0.0511002  -0.49159494]
 [ 0.37864083 -1.536274    0.02055498  0.75251347]
 [-0.35627097 -0.43150914  0.38260975 -0.23080093]
 [ 1.1160585  -0.4747366   0.3386275  -0.15355529]]
[[0.47155273 0.40640557 0.54950583 0.597276  ]
 [0.61082506 0.781309   0.4064362  0.9516289 ]
 [0.31386793 0.37946177 0.5160557  0.4453392 ]
 [0.86182237 0.43184304 0.6572833  0.25318027]]


In [40]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.6347897   0.5944471   0.2396003  -0.20985833]
 [ 0.20744768  0.43837935  0.08490339 -0.38168508]
 [-0.30463067 -0.58358973  0.21455808  0.8920585 ]
 [ 0.3208603  -0.04706916  0.25471777 -0.31214592]]


[[0.00806987 0.06745839 0.3208264  0.9494363 ]
 [0.44822264 0.667493   0.70571625 0.5015731 ]
 [0.02161384 0.8922789  0.04450595 0.56853604]
 [0.43736374 0.6587814  0.52996016 0.6057322 ]]




## Matrix Multiplication

In [48]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [31]:
a

<tf.Tensor 'Const_5:0' shape=(2, 2) dtype=int32>

In [49]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [37]:
# two rows and one columns
b = tf.constant([[10],[100]])

In [50]:
c = [[10],[100]]
type(c)
len(c)

2

In [51]:
print(b)
b.get_shape()

Tensor("Const_6:0", shape=(2, 1), dtype=int32)


TensorShape([Dimension(2), Dimension(1)])

In [52]:
result = tf.matmul(a,b)

In [53]:
result.eval()

array([[210],
       [430]])