# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
data = np.random.randint(0,100,(10,2))

In [12]:
data

array([[56, 95],
       [68, 83],
       [ 5, 62],
       [84,  1],
       [78,  4],
       [24, 56],
       [72, 42],
       [25, 32],
       [91, 20],
       [22, 48]])

In [13]:
scaler_model = MinMaxScaler()

In [14]:
scaler_model.fit(data)

C:\Users\Marcial\Anaconda3\envs\tf_1_3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
scaler_model.transform(data)

array([[ 0.59302326,  1.        ],
       [ 0.73255814,  0.87234043],
       [ 0.        ,  0.64893617],
       [ 0.91860465,  0.        ],
       [ 0.84883721,  0.03191489],
       [ 0.22093023,  0.58510638],
       [ 0.77906977,  0.43617021],
       [ 0.23255814,  0.32978723],
       [ 1.        ,  0.20212766],
       [ 0.19767442,  0.5       ]])

In [16]:
# In one step
result = scaler_model.fit_transform(data)

C:\Users\Marcial\Anaconda3\envs\tf_1_3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
result

array([[ 0.59302326,  1.        ],
       [ 0.73255814,  0.87234043],
       [ 0.        ,  0.64893617],
       [ 0.91860465,  0.        ],
       [ 0.84883721,  0.03191489],
       [ 0.22093023,  0.58510638],
       [ 0.77906977,  0.43617021],
       [ 0.23255814,  0.32978723],
       [ 1.        ,  0.20212766],
       [ 0.19767442,  0.5       ]])

In [7]:
import pandas as pd

In [4]:
data=np.random.randint(0,101,(50,4))
print(data)
len(data)

[[ 12  49  13  83]
 [ 20  91  65  31]
 [  3   1  25  13]
 [ 90  36  13  56]
 [ 84   2  22  84]
 [ 64  18   7  13]
 [ 51  73  63  42]
 [  9  29  76  89]
 [ 66  51  20  49]
 [ 94 100  70  35]
 [ 28  92  71  63]
 [ 74  13  10  25]
 [ 19  38  20  85]
 [ 37  56  75  62]
 [ 91 100  53   1]
 [ 15  39  13  66]
 [ 16  75  69  59]
 [ 57  97   5  73]
 [ 70  24   0  30]
 [ 49  85  54   0]
 [ 96  83  75  12]
 [ 20  91  32  23]
 [ 32  52  25  29]
 [ 98  71  18  33]
 [ 26  24  71  87]
 [ 71  78  41  85]
 [  4  40  72  72]
 [ 58  45  24  96]
 [ 13  81  52  25]
 [ 82  83  66  42]
 [ 38  80  10  44]
 [ 10  57  57  90]
 [ 47 100  11  71]
 [ 83  62  63  11]
 [ 74  44  10  10]
 [ 33  73  63  97]
 [ 39  32  22  36]
 [ 61  60 100  53]
 [ 75  23  57  44]
 [ 72  85  48  90]
 [ 91  44  25  42]
 [ 62  61  50  44]
 [ 82  11  27  78]
 [ 11  12  35  55]
 [ 28  96  23  78]
 [ 98  77  51  17]
 [ 10  46  47  63]
 [ 62  58  65  35]
 [ 50   9  40  97]
 [ 90  15   0  80]]


50

In [10]:
df = pd.DataFrame(data,columns=['f1','f2','f3','label'])

In [11]:
df.head()

f1  f2  f3  label
0  12  49  13     83
1  20  91  65     31
2   3   1  25     13
3  90  36  13     56
4  84   2  22     84

In [12]:
x = df[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = df['label']

In [13]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101,shuffle=True)

In [28]:
X_train.shape

(35, 3)

In [29]:
X_test.shape

(15, 3)

In [30]:
y_train.shape

(35,)

In [31]:
y_test.shape

(15,)

## Great Job!